/**
 * Formats the final response sent to the frontend.
 */
class ResponseBuilder {
    /**
     * @param {string} intent - The classified intent
     * @param {Array} data - The core data payload (e.g., foods, restaurants)
     * @param {string} friendlyMessage - The message text generated by Gemini or local fallback
     * @param {Array} actions - Suggested actions for the UI to render as buttons
     * @param {Object} extraMeta - Any additional metadata (like cold start flags)
     */
    build(intent, data = [], friendlyMessage = "", actions = [], extraMeta = {}) {
        return {
            intent: intent,
            message: friendlyMessage || this.getFallbackMessage(intent, data.length),
            foods: (intent === 'search_food' || intent === 'recommend_food') ? data : undefined,
            restaurants: intent === 'restaurant_info' ? data : undefined,
            orders: (intent === 'order_help' || intent === 'track_order') ? data : undefined,
            actions: actions,
            ...extraMeta
        };
    }

    getFallbackMessage(intent, resultCount) {
        if (resultCount === 0) return "Hmm, I couldn't find anything matching that right now. Try a different search! 🔍";
        if (intent === 'recommend_food') return `Here's what's popular right now 🔥 — ${resultCount} hot picks for you!`;
        if (intent === 'search_food') return `Here are ${resultCount} tasty options for you! 😋`;
        if (intent === 'restaurant_info') return `Found ${resultCount} restaurants! 🏪`;
        if (intent === 'order_help') return `Here are your recent orders 📦.`;
        return `Here are your results! 🎉`;
    }
}

module.exports = new ResponseBuilder();
